### ISSUE TITLE
Declarative binding of handler parameters to request elements

### ISSUE THREAD

**Issue by sergeyt** [sergeyt/Owin.Routing#16]
#TODO
* [ ] FromBodyAttribute to bind parameter to body JSON field
* [ ] FromHeadersAttribute to bind parameter to header
* [ ] FromQuery to bind parameter to query string
* if attribute is not specified parameter is bound to route variable
